#!/usr/bin/env zsh
#by With Phoenix
#
#Fixes a corrupt .zsh_history_file
#
mv ~/.zsh_history ~/.zsh_history file
strings -eS ~/.zsh_history_bad > ~/.zsh_history
#R in capital gives an error so the solution 
fc -r ~/.zsh_history
rm ~/.zsh_history_bad
